{
 "title": "Forest Nodes",
 "tags": [
  "filecoin",
  "forest"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": "label_values(job)" },
   { "name": "host", "label": "Host", "query": "label_values(instance)" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Head Epoch",
   "type": "stat",
   "description": "Latest epoch synchronized to the node.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "head_epoch{job=\"${job}\", instance=\"${host}\"}"
    }
   ]
  },
  {
   "title": "Process Wall Time",
   "type": "stat",
   "description": "Time since the Forest Node process started",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - process_start_time_seconds{job=\"$job\", instance=\"$host\"}) / 60 / 60",
     "legendFormat": "Process Wall Time"
    }
   ]
  },
  {
   "title": "Node Network Height Diff",
   "type": "timeseries",
   "description": "The difference between the node's network height and the expected network height.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "expected_network_height{instance=\"$host\"} - head_epoch{instance=\"$host\"}",
     "legendFormat": "Node Network Height Diff"
    }
   ]
  },
  {
   "title": "Tipsets Validated per Minute",
   "type": "stat",
   "description": "Number of Tipset Validated Per min",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(head_epoch{instance=\"${host}\"}[60m]) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process Virtual Memory",
   "type": "timeseries",
   "description": "Maximum amount of virtual memory available",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{job=\"${job}\", instance=\"${host}\"} / 1073741824",
     "legendFormat": "Process Virtual Memory"
    }
   ]
  },
  {
   "title": "Full Peers",
   "type": "timeseries",
   "description": "Number of healthy peers recognized by the Forest node.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "full_peers{job=\"${job}\", instance=\"${host}\"}",
     "legendFormat": "Full Peers"
    }
   ]
  },
  { "title": "RPC Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "RPC Call Count per Method",
   "type": "timeseries",
   "description": "Displays the number of times each RPC method was called on node over the specified interval.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "rpc_processing_time_count{job=\"$job\", instance=\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Recent RPC Call failures - Per method",
   "type": "timeseries",
   "description": "RPC calls failures in the given time range [1h] (Per method)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "increase(rpc_method_failure_total{job=\"$job\", instance=\"$host\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total RPC Calls Count",
   "type": "stat",
   "description": "Total RPC Calls Count",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rpc_processing_time_count{job=\"$job\", instance=\"$host\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Recent RPC Call failures",
   "type": "stat",
   "description": "RPC calls failures in the given time range [1h] (All RPC methods combined)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(rpc_method_failure_total{job=\"$job\", instance=\"$host\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Peers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Bad Peers",
   "type": "timeseries",
   "description": "Number of bad peers recognized by the node.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "bad_peers{job=\"${job}\", instance=\"${host}\"}",
     "legendFormat": "Bad Peers"
    }
   ]
  },
  {
   "title": "Message P2P Events",
   "type": "stat",
   "description": "Number of Total count of libp2p PubSub message events  recognized by the Forest Node.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "libp2p_messsage_total_total{libp2p_message_kind=\"pubsub_message_message\", job=\"$job\", instance=\"$host\"}",
     "legendFormat": "Message P2P Events"
    }
   ]
  },
  {
   "title": "Peer Disconnected P2P Events",
   "type": "stat",
   "description": "Total count of peer disconnection events recognized by the Forest Node.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "libp2p_messsage_total_total{libp2p_message_kind=\"peer_disconnected\", job=\"$job\", instance=\"$host\"}",
     "legendFormat": "Peer Disconnected P2P Events"
    }
   ]
  },
  {
   "title": "Failed Peer Requests",
   "type": "stat",
   "description": "Number of Failed Peer Requests recognized by the Forest node.",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "peer_failure_total_total{job=\"$job\", instance=\"$host\"}",
     "legendFormat": "Failed Peer Requests"
    }
   ]
  },
  {
   "title": "Peer Connected P2P Events",
   "type": "stat",
   "description": "Total count of peer connection events recognized by the Forest Node.",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "libp2p_messsage_total_total{libp2p_message_kind=\"peer_connected\", job=\"$job\", instance=\"$host\"}",
     "legendFormat": "Peer Connected P2P Events"
    }
   ]
  },
  {
   "title": "Others",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "collapsed": true,
   "panels": [
    {
     "title": "Database Size",
     "type": "stat",
     "description": "Size of Forest Node database",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 332 },
     "fieldConfig": { "defaults": { "unit": "gbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "forest_db_size{job=\"$job\", instance=\"$host\"} /  1073741824 ",
       "legendFormat": "Database Size"
      }
     ]
    },
    {
     "title": "Open File Descriptors",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 332 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_open_fds{job=\"$job\", instance=\"$host\"}",
       "legendFormat": "Open File Descriptors"
      }
     ]
    },
    {
     "title": "Process Virtual Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 340 },
     "targets": [
      {
       "expr": "process_virtual_memory_bytes{job=\"$job\", instance=\"$host\"} / 1073741824",
       "legendFormat": "Process Virtual Memory"
      }
     ]
    },
    {
     "title": "Process CPU Time",
     "type": "stat",
     "description": "Total user and system CPU time spent.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 340 },
     "fieldConfig": { "defaults": { "unit": "h" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_cpu_seconds_total{job=\"$job\", instance=\"$host\"} / 60 / 60",
       "legendFormat": "Process CPU Time"
      }
     ]
    },
    {
     "title": "Range Sync Failure Count",
     "type": "stat",
     "description": "Total count of tipset range synchronization failures encountered by the Forest node",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 348 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tipset_range_sync_failure_total_total{job=\"$job\", instance=\"$host\"}",
       "legendFormat": "Range Sync Failure Count"
      }
     ]
    }
   ]
  }
 ]
}