{
 "title": "Lotus",
 "tags": [
  "filecoin ",
  "lotus"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": "label_values(job)" },
   { "name": "host", "label": "Host", "query": "label_values(instance)" }
  ]
 },
 "panels": [
  {
   "title": "Head Epoch",
   "type": "stat",
   "description": "Latest epoch synchronized to the node.",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lotus_chain_node_height{job=\"${job}\", instance=\"${host}\"}"
    }
   ]
  },
  {
   "title": "Tipsets validated per minute",
   "type": "stat",
   "description": "Number of Tipset Validated Per min in the last 24 hours",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(lotus_chain_node_height{job=\"${job}\", instance=\"$host\"}[24h]) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lotus Node Version",
   "type": "table",
   "description": "Running Lotus Client Version ",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "lotus_info{job=\"${job}\", instance=\"${host}\"}"
    }
   ]
  },
  {
   "title": "Node Network Height Diff",
   "type": "timeseries",
   "description": "The difference between the node's network height and the expected network height.",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "lotus_chain_node_height_expected{instance=\"$host\"} - lotus_chain_node_height{instance=\"$host\"}",
     "legendFormat": "Node Network Diff"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "stat",
   "description": "Number of open file descriptors",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_open_fds{job=\"${job}\", instance=\"${host}\"}"
    }
   ]
  },
  {
   "title": "Process CPU Time",
   "type": "stat",
   "description": "Total user and system CPU time spent.",
   "gridPos": { "h": 8, "w": 4, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{job=\"${job}\", instance=\"${host}\"} / 60 / 60"
    }
   ]
  },
  {
   "title": "Process Wall Time",
   "type": "stat",
   "description": "Time since the Lotus Node process started",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - process_start_time_seconds{job=\"${job}\", instance=\"${host}\"}) / 60 / 60"
    }
   ]
  },
  {
   "title": "Filecoin Network Peers",
   "type": "timeseries",
   "description": "The current number of FIL peers",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "lotus_peer_count{job=\"${job}\", instance=\"${host}\"}"
    }
   ]
  },
  {
   "title": "Process Resident Memory",
   "type": "timeseries",
   "description": "Resident memory size",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 15 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"${job}\", instance=\"${host}\"} / 1073741824"
    }
   ]
  },
  {
   "title": "Top 5 Failed Message Producers",
   "type": "timeseries",
   "description": "Top 5 producers of failed messages due to validation failures within the Lotus system, ranked by the total count of validation failures originating from each producer.",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "topk(5, sum by (message_from) (lotus_message_failure{job=\"${job}\", instance=\"${host}\"}))"
    }
   ]
  },
  {
   "title": "Process Virtual Memory",
   "type": "timeseries",
   "description": "Maximum amount of virtual memory available",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 23 },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{job=\"${job}\", instance=\"${host}\"} / 1073741824"
    }
   ]
  },
  {
   "title": "Message Stats",
   "type": "timeseries",
   "description": "Total count of messages received ",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum(lotus_message_received{job=\"${job}\", instance=\"${host}\"})"
    }
   ]
  },
  {
   "title": "Duration for Block Validation in ms",
   "type": "timeseries",
   "description": "Average duration for block validation in milliseconds within the Lotus system, calculated over a 5-minute period. ",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(lotus_block_validation_ms_sum{job=\"${job}\",instance=\"${host}\"}[5m])/rate(lotus_block_validation_ms_count{job=\"${job}\",instance=\"${host}\"}[5m])",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}