apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: bottlerocket
  annotations:
    helm.sh/resource-policy: "keep"
spec:
  amiSelectorTerms:
  - alias: bottlerocket@latest
  role: ${node_iam_role_name}
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery/${cluster_name}: "1"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery/${cluster_name}: "1"
  tags:
    %{~ for k,v in tags ~}
    ${k}: ${v}
    %{~ endfor ~}
  detailedMonitoring: false
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 1
    httpTokens: required
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 4Gi
        volumeType: gp3
        deleteOnTermination: true
        encrypted: true
        throughput: 500
    - deviceName: /dev/xvdb
      ebs:
        volumeSize: 30Gi
        volumeType: gp3
        deleteOnTermination: true
        encrypted: true
        throughput: 500
