---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: cert-manager
spec:
  acme:
    email: "devops@${email_domain}"
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - http01:
          ingress:
            class: nginx
            IngressTemplate:
              metadata:
                annotations:
                  nginx.ingress.kubernetes.io/whitelist-source-range": "0.0.0.0/0,::/0"
                  nginx.org/mergeable-ingress-type: minion
                  traefik.ingress.kubernetes.io/frontend-entry-points: "http"
